### ISSUE TITLE
[Feature request] CURRENT_TIMESTAMP with timezone

### ISSUE THREAD

**Issue by hiroyuki-sato** [muga/embulk-filter-calcite#10]
Some users want to generate current timestamp with this plugin.
The `CURRENT_TIMESTAMP` generate the current timestamp.
However,  It generates current timestamp with UTC even if I set `default_timezone`.

The following configuration is the configuration which added the result of `embulk example` output.

```
Tue Mar 21 19:53:04 JST 2017
```

## without timezone

```yaml
filters:
  - type: calcite
#    default_timezone: "Asia/Tokyo"
    query: |-
      select id,CURRENT_TIMESTAMP from $PAGES
```

```
+---------+-----------------------------+
| ID:long | CURRENT_TIMESTAMP:timestamp |
+---------+-----------------------------+
|       1 | 2017-03-21 19:53:25.013 UTC |
|       2 | 2017-03-21 19:53:25.013 UTC |
|       3 | 2017-03-21 19:53:25.013 UTC |
|       4 | 2017-03-21 19:53:25.013 UTC |
+---------+-----------------------------+
```

## With timezone

```yaml
filters:
  - type: calcite
    default_timezone: "Asia/Tokyo"
    query: |-
      select id,CURRENT_TIMESTAMP from $PAGES
```

```
+---------+-----------------------------+
| ID:long | CURRENT_TIMESTAMP:timestamp |
+---------+-----------------------------+
|       1 | 2017-03-21 19:54:08.932 UTC |
|       2 | 2017-03-21 19:54:08.932 UTC |
|       3 | 2017-03-21 19:54:08.932 UTC |
|       4 | 2017-03-21 19:54:08.932 UTC |
+---------+-----------------------------+
```

I expected this result is the `2017-03-21 10:54:08.932`.

## Reference.

I found TIMEZONE property.

https://calcite.apache.org/apidocs/org/apache/calcite/config/CalciteConnectionProperty.html#TIME_ZONE
