### ISSUE TITLE
[Feature Request] lowercase column

### ISSUE THREAD

**Issue by hiroyuki-sato** [muga/embulk-filter-calcite#12]
The`add_time` field is an additional column by query. 
I like lowercase column name. 
It is possible to add an option (ex `use_upper_column`) for this behavior?

The following configuration is the configuration which added the result of `embulk example` output.

```yaml
filters:
  - type: calcite
    query: select *,floor(current_timestamp to SECOND) as add_time from $PAGES
```

```
*************************** 1 ***************************
      id (     long) : 1
 account (     long) : 32,864
    time (timestamp) : 2015-01-27 10:23:49 UTC
purchase (timestamp) : 2015-01-26 15:00:00 UTC
 comment (   string) : embulk
ADD_TIME (timestamp) : 2017-03-23 07:28:13 UTC
```

**Comment by muga** [comment]
Working on https://github.com/muga/embulk-filter-calcite/pull/17. https://github.com/muga/embulk-filter-calcite/pull/17 allows users to configure JDBC properties provided by Apache Calcite like:

```
- type: calcite
  default_timezone: UTC # America/Los_Angeles
  query: |
    SELECT *, floor(CURRENT_TIMESTAMP to SECOND) as add_time from $PAGES
  options:
    unquoted_casing: UNCHANGED
    case_sensitive: true
```

**Comment by hiroyuki-sato** [comment]
@muga 
Thank you. It worked as I expected.

```yaml
filters:
  - type: calcite
    default_timezone: "Asia/Tokyo"
    query: select time2 from $PAGES
    options:
      unquoted_casing: UNCHANGED
      case_sensitive: true
```

```
+-------------------------+
|         TIME2:timestamp |
+-------------------------+
| 2015-01-27 10:23:49 UTC |
| 2015-01-27 10:01:23 UTC |
| 2015-01-27 17:20:02 UTC |
| 2015-01-29 02:54:36 UTC |
+-------------------------+
```
